name: Release and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 0.1.1)'
        required: true
        default: '0.1.1'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Set Version
        run: |
          poetry version ${{ github.event.inputs.version }}
          
      - name: Build Package
        run: poetry build
        
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
